#!/usr/bin/env sh
set -eu
: "${DB_HOST:?DB_HOST is required}"; : "${DB_NAME:?DB_NAME is required}"; : "${DB_USER:?DB_USER is required}"; : "${DB_PASSWORD:?DB_PASSWORD is required}"; : "${IMPORT_HOSPITAL_ID:?IMPORT_HOSPITAL_ID is required}"; : "${IMPORT_ACTOR_USER_ID:?IMPORT_ACTOR_USER_ID is required}"; : "${EXPORT_DIR:?EXPORT_DIR must point to an export directory}"
[ "${IMPORT_CONFIRMATION:-}" = "I_UNDERSTAND_CLEAN_TARGET" ] || { echo "Set IMPORT_CONFIRMATION to I_UNDERSTAND_CLEAN_TARGET" >&2; exit 1; }
command -v mysql >/dev/null || { echo "mysql is required" >&2; exit 1; }; test -f "$EXPORT_DIR/metadata.json"; test -f "$EXPORT_DIR/database.sql"; test -f "$EXPORT_DIR/database.sql.sha256"
source_db=$(awk -F'"sourceDatabase":"' 'NF>1 {split($2,a,"\""); print a[1]}' "$EXPORT_DIR/metadata.json"); manifest_hash=$(awk -F'"sqlSha256":"' 'NF>1 {split($2,a,"\""); print a[1]}' "$EXPORT_DIR/metadata.json"); [ "$source_db" != "$DB_NAME" ] || { echo "Target DB_NAME must differ from sourceDatabase" >&2; exit 1; }
export MYSQL_PWD="$DB_PASSWORD"; actual=$(sha256sum "$EXPORT_DIR/database.sql" | awk '{print $1}'); expected=$(awk '{print $1}' "$EXPORT_DIR/database.sql.sha256"); [ "$actual" = "$expected" ] || { echo "Checksum mismatch" >&2; exit 1; }; [ "$actual" = "$manifest_hash" ] || { echo "Manifest checksum mismatch" >&2; exit 1; }
count=$(mysql --host="$DB_HOST" --port="${DB_PORT:-3306}" --user="$DB_USER" --batch --raw --skip-column-names "$DB_NAME" -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE();" | tr -d '\r\n '); [ "$count" = 0 ] || { echo "Target database must be empty" >&2; exit 1; }
mysql --host="$DB_HOST" --port="${DB_PORT:-3306}" --user="$DB_USER" "$DB_NAME" < "$EXPORT_DIR/database.sql"
mysql --host="$DB_HOST" --port="${DB_PORT:-3306}" --user="$DB_USER" "$DB_NAME" -e "INSERT INTO audit_events (hospital_id,actor_user_id,action_code,entity_type,entity_id,details) VALUES ($IMPORT_HOSPITAL_ID,$IMPORT_ACTOR_USER_ID,'portability.import','hospital',$IMPORT_HOSPITAL_ID,JSON_OBJECT('sourceDatabase','$source_db','sha256','$actual'));"
authorized=$(mysql --host="$DB_HOST" --port="${DB_PORT:-3306}" --user="$DB_USER" --batch --raw --skip-column-names "$DB_NAME" -e "SELECT COUNT(*) FROM user_roles ur JOIN role_permissions rp ON rp.hospital_id=ur.hospital_id AND rp.role_id=ur.role_id WHERE ur.hospital_id=$IMPORT_HOSPITAL_ID AND ur.user_id=$IMPORT_ACTOR_USER_ID AND rp.permission_code='data.import';" | tr -d '\r\n '); [ "$authorized" = 1 ] || { echo "Import actor is not authorized for data.import" >&2; exit 1; }
unset MYSQL_PWD; echo "Imported protected migration export into clean target $DB_NAME."
