const data = window.hospitalData;
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character])); }
function setContent() {
  $$('[data-field]').forEach((element) => { const value = element.dataset.field.split('.').reduce((result, key) => result?.[key], data); if (value !== undefined) element.textContent = value; });
  $$('[data-phone]').forEach((element) => { element.href = `tel:${data.phone.replace(/[^\d+]/g, '')}`; });
  $$('[data-whatsapp]').forEach((element) => { element.href = `https://wa.me/${data.whatsapp}`; });
  $$('[data-maps]').forEach((element) => { if (element.tagName === 'A') element.href = data.googleMapsUrl; });
  $$('[data-reviews]').forEach((element) => { element.href = data.googleReviewsUrl; });
  $$('[data-social]').forEach((element) => { element.href = data.socialLinks[element.dataset.social]; });
  $('[data-map]').src = data.googleMapsEmbed;
}
function renderTrust() { $('#trust-items').innerHTML = data.trustItems.map((item) => `<div class="trust-item"><span>${escapeHtml(item.icon)}</span><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.note)}</small></div></div>`).join(''); }
function renderStats() { $('#stats').innerHTML = data.stats.map((stat) => `<div><strong>${escapeHtml(stat.split(' ')[0])}</strong><span>${escapeHtml(stat.split(' ').slice(1).join(' '))}</span></div>`).join(''); }
function renderServices() { $('#service-grid').innerHTML = data.services.map((service) => `<article class="service-card"><span class="service-icon">${escapeHtml(service.icon)}</span><h3>${escapeHtml(service.name)}</h3><p>${escapeHtml(service.description)}</p><a href="#location" class="card-link">Contact us <span>↗</span></a></article>`).join(''); }
function renderDoctors(filter = 'All') { const doctors = filter === 'All' ? data.doctors : data.doctors.filter((doctor) => doctor.specialty === filter); $('#doctor-grid').innerHTML = doctors.map((doctor) => `<article class="doctor-card"><div class="doctor-photo"><span>${escapeHtml(doctor.initials)}</span><small>PHOTO<br>PLACEHOLDER</small></div><div class="doctor-info"><span class="tag">${escapeHtml(doctor.specialty)}</span><h3>${escapeHtml(doctor.name)}</h3><p>${escapeHtml(doctor.qualification)}</p><div class="doctor-meta"><span>⌁ ${escapeHtml(doctor.experience)}</span><span>◷ ${escapeHtml(doctor.days)}</span><span>₹ ${escapeHtml(doctor.fee.replace('₹', ''))} consultation</span></div><a href="#location" class="outline-button">Contact the hospital ↗</a></div></article>`).join(''); }
function renderTests(search = '') { const query = search.toLowerCase(); const tests = data.pathologyTests.filter((test) => `${test.name} ${test.category}`.toLowerCase().includes(query)); $('#test-list').innerHTML = tests.length ? tests.map((test) => `<article class="test-card"><div><span class="tag">${escapeHtml(test.category)}</span><h3>${escapeHtml(test.name)}</h3><p>${escapeHtml(test.preparation)}</p></div><div class="test-side"><strong>${escapeHtml(test.discount || test.price)}</strong><small>${escapeHtml(test.delivery)}</small></div></article>`).join('') : '<p class="empty-state">No matching demo tests. Try another search.</p>'; }
function renderPrices() { $('#price-table').innerHTML = data.prices.map((item) => `<tr><td><strong>${escapeHtml(item.service)}</strong></td><td>${escapeHtml(item.category)}</td><td><strong>${escapeHtml(item.price)}</strong></td><td><span class="demo-pill">${escapeHtml(item.notes)}</span></td></tr>`).join(''); }
function renderFacilities() { $('#facility-grid').innerHTML = data.facilities.map((facility) => `<div class="facility"><span>${escapeHtml(facility.icon)}</span><strong>${escapeHtml(facility.name)}</strong><small>${escapeHtml(facility.note)}</small></div>`).join(''); }
function renderReviews() { $('#review-grid').innerHTML = data.reviews.map((review) => `<article class="review-card"><div class="stars">${'★'.repeat(review.rating)}${'☆'.repeat(5 - review.rating)}</div><p>“${escapeHtml(review.text)}”</p><footer><strong>${escapeHtml(review.name)}</strong><small>${escapeHtml(review.date)}</small></footer></article>`).join(''); }
function populateDoctorFilter() { const specialties = [...new Set(data.doctors.map((doctor) => doctor.specialty))]; $('#doctor-filter').innerHTML += specialties.map((item) => `<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join(''); }
function setupInteractions() { $('#doctor-filter').addEventListener('change', (event) => renderDoctors(event.target.value)); $('#test-search').addEventListener('input', (event) => renderTests(event.target.value)); $('.menu-toggle').addEventListener('click', () => { const open = $('.main-nav').classList.toggle('is-open'); $('.menu-toggle').setAttribute('aria-expanded', open); }); $$('.main-nav a').forEach((link) => link.addEventListener('click', () => { $('.main-nav').classList.remove('is-open'); $('.menu-toggle').setAttribute('aria-expanded', 'false'); })); }
setContent(); renderTrust(); renderStats(); renderServices(); renderDoctors(); renderTests(); renderPrices(); renderFacilities(); renderReviews(); populateDoctorFilter(); setupInteractions(); $('#year').textContent = new Date().getFullYear();
